### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by RaspberryEqualsPi** [nh-server/fusee-interfacee-tk#2]
When I try to run fusee-interface-tk on my ubuntu pc, I always get some kind of python, libc error. How do I fix this?

**Comment by ihaveamac** [comment]
Please post the error output.

**Comment by noirscape** [comment]
Please post the following information:
- The output of `uname -a`
- If you're using the prebuild binary from the releases page or are running from source.

If you are running from source:
- The exact command you are using to run the application.
- The output of `python --version`.

**Comment by techmouse** [comment]
Not him but I'm having the same problem.

`[15489] Error loading Python lib '/tmp/_MEIgGjqCj/libpython3.6m.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/_MEIgGjqCj/libpython3.6m.so.1.0)`

uname -a:
`Linux GLaDOS 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by Oreo639** [comment]
Bionic Beaver uses glibc 2.27 and this was compiled for Glibc 2.28. The workaround for that is to clone the repo and just run it as a script (or run pyinstaller yourself).

**Comment by techmouse** [comment]
Yeah I tried that, too:
```
Traceback (most recent call last):
  File "app.py", line 3, in <module>
    import tkinter as tk
ModuleNotFoundError: No module named 'tkinter'
```
I installed several different libraries but none of them seem to give it the version of tkinter it wants.

**Comment by Oreo639** [comment]
You need to install the python3 version using apt or pip3

**Comment by techmouse** [comment]
Yep. Python3 was already installed.

I went with this instead:
https://github.com/Qyriad/fusee-launcher

I can keep testing though if you want this resolved.

**Comment by Oreo639** [comment]
I meant make sure you run `sudo apt install python3-tk` not `sudo apt install python-tk`

**Comment by techmouse** [comment]
Yep I installed that too and it still gave the same error.

**Comment by noirscape** [comment]
Try installing tkinter using pip.

**Comment by ihaveamac** [comment]
Is tkinter really available on pypi? I don't think so.

**Comment by noirscape** [comment]
Actually on a double check it should be in the stdlib, which means it not
being available seems more indicative of a borked python install than
anything.

**Comment by dapne** [comment]
I had this exact same issue in Debian 9. I checked my /lib/ folder and saw that libc version is below the required 2.28 version. Upgrading glibc, Debian 9 protested that the version is already at its most up-to-date. I checked the packages website and saw that only Buster (10) offered version 2.28-10 or greater. So I had to edit my sources.list and do a full upgrade to Debian 10 to fix the issue.

**Comment by Oreo639** [comment]
https://github.com/nh-server/fusee-interfacee-tk/tree/V1.0.1
The latest should work with Ubuntu 18.04 and newer, or other linux distributions with glibc 2.27 or newer.

**Comment by TheGhostboi64** [comment]
I get “no module named fusee_launcher”

**Comment by TheGhostboi64** [comment]
Never mind I just had to put in the fusee_launcher.py

**Comment by RaspberryEqualsPi** [comment]
TheGhostboi64 did you seriously just come to a 3 year old issue and make the first comment in 2 years?

**Comment by techmouse** [comment]
> TheGhostboi64 did you seriously just come to a 3 year old issue and make the first comment in 2 years?

The issue is still open. There's nothing wrong with posting in it so long as the issue is still active.

The internet police: Don't necro!
Also the internet police: This issue already exists! Don't create a new one!
I give up. There is no winning.

**Comment by TheGhostboi64** [comment]
but what if there's more problems involving Linux, like right now, I have a problem where it says "no module named mock_arguments"

**Comment by jon-torres** [comment]
> Yeah I tried that, too:
> 
> ```
> Traceback (most recent call last):
>   File "app.py", line 3, in <module>
>     import tkinter as tk
> ModuleNotFoundError: No module named 'tkinter'
> ```
> 
> I installed several different libraries but none of them seem to give it the version of tkinter it wants.

I ran into the same problem on Ubuntu 22.04.03

Apparently, it has nothing to do with tkinter. You have to add a usb rule to udev in order to make it work.

Follow the steps on this website:
https://webcfw.sdsetup.com/

> On Linux, you might get an 'Access Denied' or 'No Compatible Device' error on the Connect dialog! If you do, you can try creating a file at /etc/udev/rules.d/50-switch.rules With the following contents:
> SUBSYSTEM=="usb", ATTR{idVendor}=="0955", MODE="0664", GROUP="plugdev" and afterwards add yourself to the plugdev group by typing sudo usermod -a -G plugdev YOUR_NAME

I did not have to add myself to the plugdev group. I just used the terminal to create the "50-switch.rules" files, edit it and then saved.

I hope it helps anyone in the future with Err13 usb permission errors.
