### ISSUE TITLE
Mac OSX 10.11.6 fails at start up everytime

### ISSUE THREAD

**Issue by smilesdavis8d** [nh-server/fusee-interfacee-tk#5]
I get this error from terminal every time i run the alt version of the software. the regular version crashes as well. 
Traceback (most recent call last):
  File "app.py", line 128, in <module>
  File "app.py", line 27, in __init__
  File "app.py", line 57, in do_update
  File "fusee_launcher.py", line 135, in find_device
  File "site-packages/usb/core.py", line 1263, in find
usb.core.NoBackendError: No backend available
[82752] Failed to execute script app
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by forrest-herman** [comment]
I have this issue too, did you find a fix?

**Comment by smilesdavis8d** [comment]
I don’t believe so. I think I ended up just using a different launcher. This was so long ago I’m sorry I don’t have more information.
