### ISSUE TITLE
MacOS 10.14.6 insufficient permissions [Errno 13]

### ISSUE THREAD

**Issue by NicolasCLMendes** [nh-server/fusee-interfacee-tk#7]
Hello, I tried to mount the SD card and the shell outputs this:

```
Uploading payload...
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter/__init__.py", line 1705, in __call__
  File "app.py", line 98, in btn_mountusb_pressed
  File "fusee_launcher.py", line 688, in do_hax
  File "fusee_launcher.py", line 525, in write
  File "fusee_launcher.py", line 535, in write_single_buffer
  File "fusee_launcher.py", line 127, in write_single_buffer
  File "site-packages/usb/core.py", line 940, in write
  File "site-packages/usb/core.py", line 102, in wrapper
  File "site-packages/usb/core.py", line 216, in setup_request
  File "site-packages/usb/core.py", line 102, in wrapper
  File "site-packages/usb/core.py", line 167, in managed_claim_interface
  File "site-packages/usb/backend/libusb1.py", line 811, in claim_interface
  File "site-packages/usb/backend/libusb1.py", line 595, in _check
usb.core.USBError: [Errno 13] Access denied (insufficient permissions)
```

And the Switch keeps trying to connect with macOS... I've tried to add a rule in /etc, but that does not work at all.

**Comment by hverma4321** [comment]
Did you ever get this working?

**Comment by alexnovelli** [comment]
And the problem continues in MacOS Catalina 10.15.5...
```
usb.core.USBError: [Errno 13] Access denied (insufficient permissions)
```

**Comment by Saganic** [comment]
Any luck?
